ContosoVet/Models/Technician.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoVet.Models
{
    public class Technician : Person
    {
    }
}

ContosoVet/ViewModels/ListTechniciansViewModel.cs
using ContosoVet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoVet.ViewModels
{
    public class ListTechniciansViewModel
    {
        public IEnumerable<Technician> Technicians { get; set; }
    }
}

ContosoVet/ViewModels/TechnicianViewModel.cs
using ContosoVet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoVet.ViewModels
{
    public class TechnicianViewModel
    {
        public Technician Technician { get; set; }
    }
}

ContosoVet/Controllers/TechnicianController.cs
using ContosoVet.Interfaces;
using ContosoVet.Models;
using ContosoVet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoVet.Controllers
{
    public class TechnicianController : Controller
    {
        private ITechnicianRepository _techrepo;

        public TechnicianController(ITechnicianRepository techrepo)
        {
            _techrepo = techrepo;
        }

        public IActionResult ListTechnicians()
        {
            var techsVm = new ListTechniciansViewModel();
           techsVm.Technicians = _techrepo.GetAllTechnicians();
            return View(techsVm);
        }

        public IActionResult Technician(int id)
        {
            var techVm = new TechnicianViewModel();
            if (id == 0)
            {
                techVm = new TechnicianViewModel();
                return View(techVm);
            }
            else
            {
                techVm.Technician = _techrepo.GetTechnicianById(id);
                return View(techVm);
            }
        }

         [HttpPost]
         public IActionResult CreateTechnician(Technician technician)
        {
            var result = _techrepo.CreateTechnician(technician);
            return RedirectToAction("ListTechnicians");
        }

        [HttpPost]
        public IActionResult Update(Technician technician)
        {
            var result = _techrepo.UpdateTechnician(technician, technician.Id);
            return RedirectToAction("ListTechnicians");
        }

        public IActionResult Delete(int id)
        {
            var result = _techrepo.DeleteTechnician(id);
            return RedirectToAction("ListTechnicians");
        }

      
    }
}

ContosoVet/Views/Technician/ListTechnicians.cshtml
@model ContosoVet.ViewModels.ListTechniciansViewModel;

<br>
<br>
<br>
<br>

<div class="card-body">
    <a class="btn btn-success" asp-controller="Technician"
       asp-action="Technician"
       role="button">Add technician</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th class="text-center">Id</th>
            <th><span style="font-size:24px"></span>Name</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Address</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    @foreach (var tech in Model.Technicians)
    {
        <tbody>
            <tr>
                <td class="text-center">@tech.Id</td>
                <td>@tech.Name</td>
                <td>@tech.PhoneNumber</td>
                <td>@tech.Email</td>
                <td>@tech.Address</td>
                <td class="td-actions text-center">
                    <button type="button" rel="tooltip" class="">
                        <a asp-controller="Technician"
                           asp-action="Technician"
                           asp-route-id="@tech.Id"><span style="color:indianred"></span>Update</a>
                    </button>
                    <button type="button" rel="tooltip" class="">
                        <a asp-controller="Technician"
                           asp-action="Delete"
                           asp-route-id="@tech.Id"><span style="color:darkred"></span>Delete</a>
                    </button>
                </td>
            </tr>
        </tbody>
    }
</table>

ContosoVet/Views/Technician/Technician.cshtml
@model ContosoVet.ViewModels.TechnicianViewModel;

@if (Model.Technician == null)
{
    <div class="contact-page">
        <div id="contactUsMap" class="big-map"></div>
        <div class="main-raised">
            <div class="contact-content">
                <div class="container">
                    <h2 class="title">Create Technician</h2>
                    <div class="row">
                        <div class="col-md-6">
                            <form asp-controller="Technician" asp-action="CreateTechnician">
                                <div class="form-group">
                                    <label asp-for="Technician.Name" class="bmd-label-floating">Name</label>
                                    <input asp-for="Technician.Name" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="Technician.Email" class="bmd-label-floating">Email address</label>
                                    <input asp-for="Technician.Email" type="email" class="form-control">
                                    <span class="bmd-help"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Technician.PhoneNumber" class="bmd-label-floating">Phone</label>
                                    <input asp-for="Technician.PhoneNumber" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="Technician.Address" class="bmd-label-floating">Address</label>
                                    <input asp-for="Technician.Address" class="form-control">
                                </div>
                                <div class="submit text-center">
                                    <input type="submit" class="btn btn-success" value="Create Doctor">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
else
{
    <div class="contact-page">
        <div id="contactUsMap" class="big-map"></div>
        <div class="main-raised">
            <div class="contact-content">
                <div class="container">
                    <h2 class="title">Update Technician</h2>
                    <div class="row">
                        <div class="col-md-6">
                            <form asp-controller="Technician" asp-action="Update">
                                <div class="form-group">
                                    <label asp-for="Technician.Name" class="bmd-label-floating">Name</label>
                                    <input asp-for="Technician.Name" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="Technician.Email" class="bmd-label-floating">Email address</label>
                                    <input asp-for="Technician.Email" type="email" class="form-control">
                                    <span class="bmd-help"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Technician.PhoneNumber" class="bmd-label-floating">Phone</label>
                                    <input asp-for="Technician.PhoneNumber" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label asp-for="Technician.Address" class="bmd-label-floating">Address</label>
                                    <input asp-for="Technician.Address" class="form-control">
                                </div>
                                <div class="submit text-center">
                                    <input type="submit" class="btn btn-success" value="Update">
                                </div>
                                <div style="display: none">
                                    <input asp-for="Technician.Id" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}