ContosoVet/Controllers/AuthController.cs
using ContosoVet.Interfaces;
using ContosoVet.Models;
using ContosoVet.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ContosoVet.Controllers
{
    [Route("auth")]
    public class AuthController : Controller
    {
        private IUserService _userService;

        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        [Route("signup")]
        public IActionResult Signup()
        {
            var svm = new SignupViewModel();
            return View(svm);
        }

        [HttpPost]
        [Route("signup")]
        public IActionResult Signup(Admin admin)
        {
            if (ModelState.IsValid)
            {
                _userService.CreateAdmin(admin);
                return RedirectToAction("Login");
            }
            return View(admin);
        }

        [Route("login")]
        public IActionResult Login()
        {
            var lvm = new LoginViewModel();
            return View(lvm);
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(LoginViewModel lvm)
        {
            if (ModelState.IsValid)
            {
                Admin admin;
                if (_userService.ValidateCredentials(lvm.Username, lvm.Password, out admin))
                {
                    await SignIn(admin);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(lvm);
        }

        public async Task<IActionResult> Signout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        private async Task SignIn(Admin admin)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, admin.Username),
                new Claim("name", admin.Name)
            };

            var identity = new ClaimsIdentity(claims,
                CookieAuthenticationDefaults.AuthenticationScheme, //"cookie"
                "name",
                null);
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(principal);
        }

    }
}

ContosoVet/Controllers/ClientController.cs
using ContosoVet.Interfaces;
using ContosoVet.Models;
using ContosoVet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoVet.Controllers
{
    
    public class ClientController : Controller
    {
        private IClientRepository _clientRepo;

        public ClientController(IClientRepository clientRepo)
        {
            _clientRepo = clientRepo;
        }

        public IActionResult ListClients()
        {
            var clientsVm = new ListClientsViewModel();
            clientsVm.Clients = _clientRepo.GetAllClients();
            return View(clientsVm);
        }

        public IActionResult Client(int id)
        {
            var clientVm = new ClientViewModel();

            if (id == 0)
            {
                clientVm = new ClientViewModel();
                return View(clientVm);
            }
            else
            {
                clientVm.Client = _clientRepo.GetClientById(id);
                return View(clientVm);
            }
        }

        [HttpPost]
        public IActionResult CreateClient(Client client)
        {
            _clientRepo.CreateClient(client);
            return RedirectToAction("ListClients");
        }

        [HttpPost]
        public IActionResult Update(Client client)
        {
            var result = _clientRepo.UpdateClient(client, client.Id);
            return RedirectToAction("ListClients");
        }

        public IActionResult Delete(int id)
        {
            var result = _clientRepo.DeleteClient(id);
            return RedirectToAction("ListClients");
        }

    }
}

ContosoVet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ContosoVet</title>

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="~/css/material-kit.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg bg-dark" style="margin:0">
        <div class="container">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" style="background-color:white" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar navbar-kebab">Menu</span>
                <span class="navbar-toggler-bar navbar-kebab"></span>
                <span class="navbar-toggler-bar navbar-kebab"></span>
            </button>

            @*<div class="collapse navbar-collapse" id="navbarNav ">
        <ul class="navbar-nav align-content-center">*@
            @if (Context.User.Identity.IsAuthenticated)
            {
                <div class="collapse navbar-collapse" id="navbarNav ">
                    <ul class="navbar-nav  navbar-left">

                        <li class="nav-item" style="float:left">
                            <a asp-controller="Client" asp-action="ListClients" class="nav-link"><span style="display:block"><span style="padding:2px">Client</span></span></a>
                        </li>
                        <li class="nav-item" style="float:left">
                            <a asp-controller="Doctor" asp-action="ListDoctors" class="nav-link"><span style="display:block"><span style="padding:2px">Doctor</span></span></a>
                        </li>
                        <li class="nav-item" style="float:left">
                            <a asp-controller="Technician" asp-action="ListTechnicians" class="nav-link"><span style="display:block"><span style="padding:2px">Technician</span></span></a>
                        </li>
                        <li class="nav-item" style="float:left">
                            <a asp-controller="Patient" asp-action="ListPatients" class="nav-link"><span style="display:block"><span style="padding:2px">Patient</span></span></a>
                        </li>
                        <li class="nav-item" style="float:left">
                            <a asp-controller="Appointment" asp-action="ListAppointments" class="nav-link"><span style="display:block"><span style="padding:2px">Schedules</span></span></a>
                        </li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item" style="float:left">
                            <span class="navbar-text">
                                Logged in: @Context.User.Identity.Name
                            </span>
                        </li>

                        <li class="nav-item" style="float:left">
                            <a asp-controller="Auth" , asp-action="Signout" class="nav-link"><span style="display:block"><span style="padding:2px">Sign out</span></span></a>
                        </li>
                    </ul>
                    @*</ul>
                </div>*@

                </div>
            }

            else
            {
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item" style="float:left">
                        <a asp-controller="Auth" asp-action="Login" class="nav-link"><span style="display:block"><span style="padding:2px">Log in</span></span></a>
                    </li>
                    <li class="nav-item" style="float:left">
                        <a asp-controller="Auth" asp-action="Signup" class="nav-link"><span style="display:block"><span style="padding:2px">Sign up</span></span></a>
                    </li>

                </ul>
            }
                </div>
    </nav>


            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; 2019 - ContosoVet</p>
                </footer>
            </div>



            @RenderSection("Scripts", required: false)
            <script src="~/js/jquery.min.js" type="text/javascript"></script>
            <script src="~/js/popper.min.js" type="text/javascript"></script>
            <script src="~/js/bootstrap-datetimepicker.js" type="text/javascript"></script>
            <script src="~/js/bootstrap-material-design.min.js" type="text/javascript"></script>
            <script src="~/js/bootstrap-selectpicker.js" type="text/javascript"></script>
            <script src="~/js/bootstrap-tagsinput.js" type="text/javascript"></script>
            <script src="~/js/jasny-bootstrap.min.js" type="text/javascript"></script>
            <script src="~/js/jquery.flexisel.js" type="text/javascript"></script>
            <script src="~/js/material-kit.js" type="text/javascript"></script>
            <script src="~/js/moment.min.js" type="text/javascript"></script>
            <script src="~/js/nouislider.min.js" type="text/javascript"></script>
</body>
</html>